<#
.SYNOPSIS
    Discover this Claude Code session's own session_id by round-tripping a distinctive marker
    through sdp-hook-log.ps1's own logged output, then reading it back.

.PARAMETER marker
    Required. A plain-ASCII marker string, generated by the caller (mechanical value generation
    only, e.g. a GUID fragment - no LLM judgment involved) and passed in literally so this exact
    invocation's own tool_input is what sdp-hook-log.ps1 logs the marker under. Non-ASCII glyphs
    are confirmed corrupted somewhere in the hook-logging pipeline - callers must not use them.

.NOTES
    Reads:
      .sdp-solution-workflow/logging/hook-logs/hook-log-<local yyyyMMdd>.jsonl
    Writes: nothing.
    Stdout: single-line JSON result object.
    Exit codes: 0 = success or non-blocking not-found (status distinguishes); 1 = missing/invalid
    parameter (operational error).

    Why a marker round-trip: session_id is only available inside hook input JSON delivered to
    hook scripts via stdin - no environment variable exposes it to a running session. This script
    is itself invoked as a PowerShell tool call carrying -marker literally in its command text, so
    sdp-hook-log.ps1's PreToolUse/PostToolUse hook logs that exact marker in tool_input alongside
    this call's own session_id. Reading today's hook-log back for the marker recovers session_id
    without any other discovery channel.

    Async timing: sdp-hook-log.ps1 is registered as an async hook, so its write is not guaranteed
    to have completed by the time this script starts polling. Retry budget: 5 attempts, 2-second
    backoff between attempts (10-second total poll budget) before giving up.

    Torn-line tolerance: a line that fails JSON parsing is treated as an in-flight async write not
    yet fully flushed, not a fatal error - it is skipped, not surfaced as a failure.

    Result envelope: { "status": "success"|"not_found"|"error", "session_id": <string|null>,
    "error": <string|null> }. "not_found" (marker never appeared within the retry budget) is a
    non-blocking expected condition, not a script error - callers treat it the same as "error" for
    the purpose of skipping this fire's budget check, but it is distinguished in the envelope for
    diagnosability.
#>
param(
    [string]$marker = ""
)

function Write-Result($obj) {
    Write-Output ($obj | ConvertTo-Json -Compress -Depth 5)
}

if (-not $marker) {
    Write-Result @{ status = "error"; session_id = $null; error = "Required parameter -marker was not provided." }
    exit 1
}

$solutionRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$today = Get-Date -Format "yyyyMMdd"
$logPath = Join-Path $solutionRoot ".sdp-solution-workflow/logging/hook-logs/hook-log-$today.jsonl"

function Find-MarkerSessionId([string]$path, [string]$needle) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { return $null }
    $lines = Get-Content -LiteralPath $path -Encoding UTF8 -ErrorAction SilentlyContinue
    if (-not $lines) { return $null }
    foreach ($line in $lines) {
        if (-not $line) { continue }
        if ($line -notlike "*$needle*") { continue }
        try {
            $entry = $line | ConvertFrom-Json
        } catch {
            # Torn line - an in-flight async write not yet fully flushed. Skip, not a failure.
            continue
        }
        if ($entry.session_id) { return "$($entry.session_id)" }
    }
    return $null
}

$maxAttempts = 5
$backoffSeconds = 2
$found = $null
for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
    $found = Find-MarkerSessionId -path $logPath -needle $marker
    if ($found) { break }
    if ($attempt -lt $maxAttempts) { Start-Sleep -Seconds $backoffSeconds }
}

if ($found) {
    Write-Result @{ status = "success"; session_id = $found; error = $null }
    exit 0
}

Write-Result @{ status = "not_found"; session_id = $null; error = "Marker not found in today's hook-log within the retry budget ($maxAttempts attempts, ${backoffSeconds}s backoff)." }
exit 0
