<#
.SYNOPSIS
    Count distinct subagents spawned under a given (or self-discovered) Claude Code session_id,
    by counting distinct non-null agent_id values in the hook-log - an exact match to the
    platform's own cumulative-lifetime subagent-spawn count, not an approximation.

.PARAMETER sessionId
    Optional. The session_id to count against. If absent, this script performs its own
    marker-embed-and-poll discovery inline (the same technique sdp-claude-session-get-sessionid.ps1
    uses) rather than shelling out to that script as a nested subprocess - a nested,
    non-tool-dispatched process call is never observed by Claude Code's own hook system, so the
    discovery logic must run as part of this script's own top-level invocation to be observed
    correctly.

.PARAMETER marker
    Required only when -sessionId is absent. Same contract as sdp-claude-session-get-sessionid.ps1's
    -marker: a plain-ASCII marker generated by the caller and passed in literally so this exact
    invocation's own tool_input is what sdp-hook-log.ps1 logs the marker under.

.NOTES
    Reads:
      .sdp-solution-workflow/logging/hook-logs/hook-log-<local yyyyMMdd>.jsonl (today)
      .sdp-solution-workflow/logging/hook-logs/hook-log-<local yyyyMMdd minus 1>.jsonl (yesterday)
    Writes: nothing.
    Stdout: single-line JSON result object.
    Exit codes: 0 = success or non-blocking not-found; 1 = missing/invalid parameter (operational
    error).

    Both files are always read, unconditionally - no "near midnight" conditional. Simpler, and
    avoids any boundary-condition risk of a session that spans local midnight. Cost is two small
    file reads per call; accepted as trivial against the boundary-condition risk it avoids.

    Torn-line tolerance: a line that fails JSON parsing is treated as an in-flight async write not
    yet fully flushed, not a fatal error - it is skipped, not surfaced as a failure. Same rule as
    sdp-claude-session-get-sessionid.ps1's own marker poll.

    Result envelope: { "status": "success"|"not_found"|"error", "session_id": <string|null>,
    "agent_count": <int|null>, "error": <string|null> }. "not_found" applies only to the
    self-discovery path (marker never appeared within the retry budget) - a resolved session_id
    with zero matching agent_id entries is still "success" with agent_count 0.
#>
param(
    [string]$sessionId = "",
    [string]$marker = ""
)

function Write-Result($obj) {
    Write-Output ($obj | ConvertTo-Json -Compress -Depth 5)
}

$solutionRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)

function Get-HookLogPath([datetime]$date) {
    $stamp = $date.ToString("yyyyMMdd")
    return Join-Path $solutionRoot ".sdp-solution-workflow/logging/hook-logs/hook-log-$stamp.jsonl"
}

function Read-JsonlEntries([string]$path) {
    $result = New-Object System.Collections.Generic.List[object]
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { return $result }
    $lines = Get-Content -LiteralPath $path -Encoding UTF8 -ErrorAction SilentlyContinue
    if (-not $lines) { return $result }
    foreach ($line in $lines) {
        if (-not $line) { continue }
        try {
            $entry = $line | ConvertFrom-Json
        } catch {
            # Torn line - an in-flight async write not yet fully flushed. Skip, not a failure.
            continue
        }
        $result.Add($entry)
    }
    return $result
}

# ---------------------------------------------------------------------------
# Resolve session_id - either passed in, or self-discovered via the same
# marker-embed-and-poll technique as sdp-claude-session-get-sessionid.ps1,
# run inline (not shelled out) so Claude Code's hook system observes this
# exact top-level invocation's own tool_input.
# ---------------------------------------------------------------------------

$resolvedSessionId = $sessionId

if (-not $resolvedSessionId) {
    if (-not $marker) {
        Write-Result @{ status = "error"; session_id = $null; agent_count = $null; error = "Neither -sessionId nor -marker was provided; self-discovery requires -marker." }
        exit 1
    }

    $todayPath = Get-HookLogPath (Get-Date)
    $maxAttempts = 5
    $backoffSeconds = 2
    $found = $null
    for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
        foreach ($entry in (Read-JsonlEntries $todayPath)) {
            $entryLine = $entry | ConvertTo-Json -Compress -Depth 5
            if ($entryLine -like "*$marker*" -and $entry.session_id) {
                $found = "$($entry.session_id)"
                break
            }
        }
        if ($found) { break }
        if ($attempt -lt $maxAttempts) { Start-Sleep -Seconds $backoffSeconds }
    }

    if (-not $found) {
        Write-Result @{ status = "not_found"; session_id = $null; agent_count = $null; error = "Marker not found in today's hook-log within the retry budget ($maxAttempts attempts, ${backoffSeconds}s backoff)." }
        exit 0
    }
    $resolvedSessionId = $found
}

# ---------------------------------------------------------------------------
# Count distinct non-null agent_id values across today's and yesterday's
# hook-log files where session_id matches.
# ---------------------------------------------------------------------------

$todayEntries = Read-JsonlEntries (Get-HookLogPath (Get-Date))
$yesterdayEntries = Read-JsonlEntries (Get-HookLogPath ((Get-Date).AddDays(-1)))

$agentIds = New-Object System.Collections.Generic.HashSet[string]
foreach ($entry in @($todayEntries) + @($yesterdayEntries)) {
    if ("$($entry.session_id)" -ne $resolvedSessionId) { continue }
    if ($entry.agent_id) { [void]$agentIds.Add("$($entry.agent_id)") }
}

Write-Result @{ status = "success"; session_id = $resolvedSessionId; agent_count = $agentIds.Count; error = $null }
exit 0
